const constants = {
  // Exercises
  ADD_NEW_EXERCISE: "ADD_NEW_EXERCISE",
  REMOVE_EXERCISE: "REMOVE_EXERCISE",
  REMOVE_SCHEDULE_DAY_EXERCISE: "REMOVE_SCHEDULE_DAY_EXERCISE",
  CHOOSE_SCHEDULE_DAY_EXERCISE: "CHOOSE_SCHEDULE_DAY_EXERCISE",
}

export default constants