const constants = {
  // Exercises
  ADD_NEW_EXERCISE: "ADD_NEW_EXERCISE",
  REMOVE_EXERCISE: "REMOVE_EXERCISE",
  REMOVE_SCHEDULE_EXERCISE: "REMOVE_SCHEDULE_EXERCISE",
  CHOOSE_EXERCISE: "CHOOSE_EXERCISE",
}

export default constants